apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: isilon
provisioner: isilon.com/isilon
parameters:
  server: 192.168.5.200
  apiserver: 192.168.4.200
  basepath: /ifs/test
  apiuser: "admin"
  secretNamespace: "default"
  secretName: "cluster1-password"
  group: Users
  quotas: "false"
  zone: "System"
mountOptions:
  - nfsvers=3
  - nolock
