kind: Pod
apiVersion: v1
metadata:
  name: k8s-isi-provisioner
spec:
  containers:
    - name: k8s-isi-provisioner
      image: tenortim/k8s_isi_provisioner:latest
      imagePullPolicy: "IfNotPresent"
  serviceAccount: k8s-isi-provisioner
